### ISSUE TITLE
Can not enter PIN

### ISSUE THREAD

**Issue by CopyAce** [DumbWareio/DumbPad#13]
**Describe the bug**
I can not enter the PIN when connected via Tailscale. Possibly due to native URL not matching?

**To Reproduce**
1. Enter site address using Tailscale pre-fix IP address. 
2. Login page loads but PIN can not be entered. 

**Expected behavior**
I would expect to be able to enter PIN

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sloniupl** [comment]
Same issue for me but i'm not able to enter pin at all (fresh deployment).
Works great without PIN set, after setting pin there is nowhere to type it in:

![Image](https://github.com/user-attachments/assets/fe25b053-4777-4b51-aa33-487606d43198)

**Comment by abiteman** [comment]
> Same issue for me but i'm not able to enter pin at all (fresh deployment).
> Works great without PIN set, after setting pin there is nowhere to type it in:
> 
> ![Image](https://github.com/user-attachments/assets/fe25b053-4777-4b51-aa33-487606d43198)

And to confirm, you're using Tailscale as well?

**Comment by sloniupl** [comment]
> > Same issue for me but i'm not able to enter pin at all (fresh deployment).
> > Works great without PIN set, after setting pin there is nowhere to type it in:
> > ![Image](https://github.com/user-attachments/assets/fe25b053-4777-4b51-aa33-487606d43198)
> 
> And to confirm, you're using Tailscale as well?

I don't use Tailscale, I just access it via my local network:

here is my yaml config if it helps:

```
services:
  dumbpad:
    image: dumbwareio/dumbpad:latest
    container_name: dumbpad
    restart: unless-stopped
    ports:
      - 3100:3000
    volumes:
      # Where your notes will be stored
      - /mnt/dane/container/dumbpad:/app/data
    environment:
      # The title shown in the web interface
      SITE_TITLE: GłupiNotatnik
      # Optional PIN protection (leave empty to disable)
      DUMBPAD_PIN: 1234
      # The base URL for the application
      # BASE_URL: http://localhost:3100
```
