### ISSUE TITLE
Cannot enter PIN, nor save or create new note

### ISSUE THREAD

**Issue by jerdzho** [DumbWareio/DumbPad#42]
![Image](https://github.com/user-attachments/assets/de9b81dc-ee56-49e8-8033-5f45bfb19c7a)

Docker-compose.yml was copied from github.

So I disabled PIN. When I try to save notes, it says:

![Image](https://github.com/user-attachments/assets/111d8eed-c2ac-4d8a-a1b9-02b5c27524c5)

Same while trying to add new note:

![Image](https://github.com/user-attachments/assets/60580a2d-ce56-43ec-b59b-0ee0ca43205e)

Logs:

![Image](https://github.com/user-attachments/assets/829fd3b4-9f52-4b87-8acf-11e0b3f74c16)

**Comment by explicitworkload** [comment]
same issue here if i turned on DUMBPAD_PIN.

**Comment by explicitworkload** [comment]
docker image seems fine on my ARM, but doesn't work on x86.

**Comment by gitmotion** [comment]
hey there @jerdzho by any chance were there any errors in the dev console when you couldn't see the pin input?

**Comment by gitmotion** [comment]
PR: https://github.com/DumbWareio/DumbPad/pull/44
with this fix you should be able to comment out base_url or have it defined

**Comment by jerdzho** [comment]
Error was, that I didn't set URL in docker-compose.yml to http://ip:port, but left it as http://localhost:port  .. Sorry for raising false alarm, it works like charm now.

**Comment by gitmotion** [comment]
quick note for those that look through these issues for fixes - PR: https://github.com/DumbWareio/DumbPad/pull/45
- after the recent change to add ALLOWED_ORIGINS, if you wish to add additional urls/domains you can add them in the docker compose or allow '*' view the new env variable. (make sure to include the NODE_ENV: production as well)
- this should allow you expose with an authentication provider like authentik/etc as well and install as a pwa

view newly updated docker compose: https://github.com/gitmotion/DumbPad/blob/905960b1360c207202d6bf6fa1071a0430dfd1cf/docker-compose.yml

**Comment by gitmotion** [comment]
changes from #52 
- should allow you to remove `NODE_ENV` and `ALLOWED_ORIGINS` variables from your compose.
- by default allow all is enabled
- to restrict origins you only need to declare  the `ALLOWED_ORIGINS` variable in your compose / env (no more NODE_ENV needed)

that is all 🙏🏻

`docker-compose.yml` example:
```yaml
services:
  dumbpad:
    image: dumbwareio/dumbpad:latest
    container_name: dumbpad
    restart: unless-stopped
    ports:
      - ${DUMBPAD_PORT:-3000}:3000
    volumes:
      - ${DUMBPAD_DATA_PATH:-./data}:/app/data
    environment:
      # The title shown in the web interface
      SITE_TITLE: ${DUMBPAD_SITE_TITLE:-DumbPad}
      # Optional PIN protection (leave empty to disable)
      DUMBPAD_PIN: ${DUMBPAD_PIN:-}
      # The base URL for the application
      BASE_URL: ${DUMBPAD_BASE_URL:-http://localhost:3000} # Use ALLOWED_ORIGINS below to restrict cors to specific origins
      # (OPTIONAL)
      # Usage: Comma-separated list of urls: http://localhost:port,http://internalip:port,https://base.proxy.tld,https://authprovider.domain.tld
      # ALLOWED_ORIGINS: ${DUMBPAD_ALLOWED_ORIGINS:-http://localhost:3000} # Comment out to allow all origins (*)
      # LOCKOUT_TIME: ${DUMBPAD_LOCK_TIME:-15} # Customize pin lockout time (if empty, defaults to 15 in minutes)
      # MAX_ATTEMPTS: ${DUMBPAD_MAX_ATTEMPTS:-5} # Customize pin max attempts (if empty, defaults to 5)
      # COOKIE_MAX_AGE: ${DUMBPAD_COOKIE_MAX_AGE:-24} # Customize maximum age of cookies primarily used for pin verification (default 24) in hours
      # PAGE_HISTORY_COOKIE_AGE: ${DUMBPAD_PAGE_HISTORY_COOKIE_AGE:-365} # Customize age of cookie to show the last notepad opened (default 365 | max 400) in days - shows default notepad on load if expired
```
